language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
env:
  global:
    - secure: d4woA9SqqJhEbjsSVZXPovrIhEsVkbrncyxyTfgeBSTMqgGSNyKuaHN2kNVy+3e7z9PDNBDIkq91emsPW+ShlmYxvv6pqEKRVPVauIuy6amTH3bMpPHIjlniTB1GfgiWNWNZiD+DOEIjLiMyt5e/QAQjoJMUFhIF5O9ke+qjC8M=
    - secure: XrhwC5gdhj+4Ir8lobL2lQRobWeuFC3uKMdG5KPUbnyCDJz7laLsxMbLwsLp1H2w+YUBUkkb3W2xMa++SZaTQGiclOa9XqkhHaALDntSe1d6Qh3uMxX7IrbhQdmNhG45+MLbud8d3rTIunpU8Fy1qe4HiesBBxU43d0aCfneghM=
    - secure: Zc9qVmVjdjYrVCpGbIQ75rAHfzKI0naL/ym2BzJ+u4UrlN6PJ91y69Q2dEO2yCkns4TpG0nog6RHpF89S5mdtV141d7Kb4yC5DCgwSJloYsIm6LEX+g117dc8s+ZcZ2uspdCFo2XKaQ2Gij/2vxuelDg32acxlTP5BFJX2WcQ2U=
notifications:
  hipchat:
    rooms:
      - secure: g/T/lE7I5UznbVLLQhpOVoziU9qpx3WfDjg1BXZbAZyZfbujRcQhlo6ZIJjLUDnQEUJx6ZEaZETnDqnTKaOou/fzSHvUBqgdpb8z/DKwhmIx/htYEE36NTZSdd6Y0B5A4rVOQJ970blJsanioIxhDCt765TUCmy99ynH3FSFY7s=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: always
branches:
  only:
    - master
    - documentation
